### ISSUE TITLE
Fix spacing issues.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Site#11]
![screenshot from 2017-01-19 10-27-10](https://cloud.githubusercontent.com/assets/1911594/22101027/e2bffdc6-de31-11e6-9158-2ad1f52c2d8a.png)

**Comment by MeanEYE** [comment]
![screenshot from 2017-01-19 10-35-37](https://cloud.githubusercontent.com/assets/1911594/22101269/07e4644c-de33-11e6-8145-6140f7720232.png)

**Comment by iliyaM** [comment]
fixed
