### ISSUE TITLE
Send / submit button should have the right cursor when hover

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Primavera-Site#2]
On hover change the regular cursor to a cursor.pointer - ALWAYS

**Comment by MeanEYE** [comment]
Buttons never have pointer cursor. Only links. Why is this an issue? If design language is clear enough there shouldn't be a confusion about whether something is a button and if it's clickable or not.

**Comment by iliyaM** [comment]
make a decision please and close or comment the issue

**Comment by hanan-avzuk** [comment]
II think that each object that is clickable and does something should the cursor.pointer. But this is up to you, you are the one deciding this.

**Comment by MeanEYE** [comment]
Hover and active effect is enough.
