### ISSUE TITLE
On mobile version remove envelope icon.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Primavera-Site#23]
On the mobile version, remove the envelope icon.

![image](https://cloud.githubusercontent.com/assets/26923359/26200665/ec0fbe62-3bd7-11e7-91f5-6d8df201dfcb.png)

**Comment by MeanEYE** [comment]
@iliyaM is this something we added?

**Comment by iliyaM** [comment]
no. its not us. at least not me

בתאריך 21 במאי 2017 14:43,‏ "Mladen Mijatov" <notifications@github.com> כתב:

**Comment by MeanEYE** [comment]
@talovdat check with Eyal and make sure they are not adding this as a widget through Google Tag Manager, since neither Iliya nor me remember this being added.

**Comment by talovdat** [comment]
In the discussion at these moments. 
They are going to do it alone because they disconnected Eyal from the GTM. Again.
I am closing the issue.
