### ISSUE TITLE
Dialog window showing for smaller screens

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/Primavera-Site#24]
I would suggest to change the top definition on div.dialog to -200% so no matter how small the screen is it will never show unless the dialog is required to show.

**Comment by eyalway2cu** [comment]
![img-20170620-wa0011](https://user-images.githubusercontent.com/7808985/27384687-6ffddfd0-5698-11e7-87a8-97318655976f.jpg)
This image demonstrates the issue as mentioned above.

**Comment by MeanEYE** [comment]
@VladimirWebDev check if this is still happening on TTM on mobile. I think it's fixed with new Dialog styles.

**Comment by VladimirWebDev** [comment]
This is local test.
@MeanEYE This is current situation on mobile:

![image](https://user-images.githubusercontent.com/25882157/33625327-7dfb2506-d9f7-11e7-994c-83b987aa1302.png)
Video will be visible. However fixed header is generally crossing div.dialog.visible and title of dialog is not visible. Dialog is positioned 10% from top. Height of fixed header is a bit bigger than needed. 
If dialog top position is increased by 3%
![image](https://user-images.githubusercontent.com/25882157/33625883-557c7dc6-d9f9-11e7-8088-9032a0d3e130.png)
There is missing div.title if needed.

**Comment by MeanEYE** [comment]
Issue reported here is about hidden dialog being visible. And I don't think that's an issue anymore. However, this issue you are talking about should be handled with proper `z-index`.

**Comment by VladimirWebDev** [comment]
Original issue is not longer present. Issue I find is solved with bigger z-index so when dialog is open it comes on top of everything and there is no more crossing by fixed header.
