### ISSUE TITLE
Make system load different video size and quality 

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Primavera-Site#9]
Implement the 3 different video sizes and quality

**Comment by iliyaM** [comment]
correct me if i am wrong but we are not using the system for the video we are embedding a video file. 
to make 3 different video qualities we need to have 3 video files each one with different quality

**Comment by MeanEYE** [comment]
I don't know what you mean by system, but we are using native browser support to play videos. We are not using any service like YouTube. We do have different video qualities, the issue here is to find a way for browser to automatically play the best possible quality possible for user to stream.
